version: '3'
services:
  master:
    build: ./image
    command: sh /root/master.sh
    ports:
      - "8080:8080"
      - "7077:7077"
  slave1:
    build: ./image
    command: sh /root/slave.sh
    ports:
      - "8081:8081"
  slave2:
    build: ./image
    command: sh /root/slave.sh
    ports:
      - "8082:8081"
