version: '3'
services:
  tcp:
    build: ./tcp
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  master:
    image: spark-standalone
    command: sh /root/master.sh
    ports:
      - "8080:8080"
      - "7077:7077"
  slave1:
    image: spark-standalone
    command: sh /root/slave.sh spark://master:7077
    ports:
      - "8081:8081"
  # slave2:
  #   image: spark-standalone
  #   command: sh /root/slave.sh spark://master:7077
  #   ports:
  #     - "8082:8081"
